# Generated by Django 5.2.1 on 2025-05-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
